---
name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: pip install hatch
      - name: "Run linting checks"
        run: hatch run check
      - name: "Build package & docs"
        run: |
          hatch build
          hatch run docs:build
      - name: "Run tests with SQLite"
        env:
          TEST_DATABASE_URI: "sqlite:///test.db"
        run: hatch run test
      - name: "Enforce coverage"
        run: hatch run cov
      - name: "Upload Coverage"
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
